service: test-sns-notification
app: testsnsnotification
org: garethmccumskey
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - schedule: rate(5 minutes)